### ISSUE TITLE
Pip install and running command results command not found

### ISSUE THREAD

**Issue by Atihinen** [eriwen/lcov-to-cobertura-xml#23]
According to documentation https://github.com/eriwen/lcov-to-cobertura-xml#with-pip there should be command `lcov_cobertura` but there isn't.

Result is command not found.

Tested with ubuntu 14.04 with python 2.7.11

Tested with virtualenv and without.

Package versions which I tried were: 1.0, 1.1, 1.1.1, 1.2, 1.3, 1.4, 1.5, 1.6 and none of those gave me command `lcov_cobertura`

**Comment by gsauthof** [comment]
I can confirm, the latest currently released version (1.6) doesn't install the `lcov_covertura` executable.

The online documentation documents the post-1.6 state of the art. In fact, this is the post 1.6 commit that added this feature: 8c55cd11f80a21e7e46f20f8c81fcde0bf11f5e5

Thus, until 1.7 gets uploaded pypi, you can just install the head version with pip to get the command installed, as well, e.g.:

    git clone https://github.com/eriwen/lcov-to-cobertura-xml.git
    cd lcov-to-cobertura-xml/
    pip3 install .

Or even:

    pip3 install git+https://github.com/eriwen/lcov-to-cobertura-xml.git

**Comment by carlosmmelo** [comment]
Thanks for the workaround @gsauthof
