### ISSUE TITLE
Missing function & statement metrics

### ISSUE THREAD

**Issue by mickyjohnstonmonotype** [eriwen/lcov-to-cobertura-xml#28]
I ran lcov-to-cobertura against a lcov results file and while the conversion worked (i.e. coverage.xml was produced), I do not see function and statement summary metrics in this file. Note, I do see branch and line summary metrics:

`<coverage branch-rate="0.6012965964343598" branches-covered="742" branches-valid="1234" complexity="0" line-rate="0.703875968992248" lines-covered="1362" lines-valid="1935" timestamp="1505846593" version="2.0.3">`

**Comment by eriwen** [comment]
I'm afraid that there's not enough detail here to action on. Please provide an example lcov file which does not work as expected.
